import Data.Maybe (listToMaybe)

data Known = Known {
      children :: Int,
      cats :: Int,
      samoyeds :: Int,
      pomeranians :: Int,
      akitas :: Int,
      vizslas :: Int,
      goldfish :: Int,
      trees :: Int,
      cars :: Int,
      perfumes :: Int
    }

data Remembered = Remembered {
      mchildren :: Maybe Int,
      mcats :: Maybe Int,
      msamoyeds :: Maybe Int,
      mpomeranians :: Maybe Int,
      makitas :: Maybe Int,
      mvizslas :: Maybe Int,
      mgoldfish :: Maybe Int,
      mtrees :: Maybe Int,
      mcars :: Maybe Int,
      mperfumes :: Maybe Int
    } deriving (Eq, Show, Read)

data Sue = Sue Int Remembered deriving (Eq, Show, Read)

defRemembered :: Remembered
defRemembered = Remembered {
                  mchildren = Nothing,
                  mcats = Nothing,
                  msamoyeds = Nothing,
                  mpomeranians = Nothing,
                  makitas = Nothing,
                  mvizslas = Nothing,
                  mgoldfish = Nothing,
                  mtrees = Nothing,
                  mcars = Nothing,
                  mperfumes = Nothing
                }

input :: [Sue]
input = [Sue 1 (defRemembered { mcars = Just 9, makitas = Just 3, mgoldfish = Just 0 }),
         Sue 2 (defRemembered { makitas = Just 9, mchildren = Just 3, msamoyeds = Just 9 }),
         Sue 3 (defRemembered { mtrees = Just 6, mcars = Just 6, mchildren = Just 4 }),
         Sue 4 (defRemembered { mtrees = Just 4, mvizslas = Just 4, mgoldfish = Just 9 }),
         Sue 5 (defRemembered { makitas = Just 9, mvizslas = Just 7, mcars = Just 5 }),
         Sue 6 (defRemembered { mvizslas = Just 6, mgoldfish = Just 6, makitas = Just 3 }),
         Sue 7 (defRemembered { mpomeranians = Just 5, msamoyeds = Just 0, mperfumes = Just 10 }),
         Sue 8 (defRemembered { mcars = Just 10, mpomeranians = Just 7, mgoldfish = Just 8 }),
         Sue 9 (defRemembered { mtrees = Just 2, mvizslas = Just 7, msamoyeds = Just 6 }),
         Sue 10 (defRemembered { mperfumes = Just 5, mpomeranians = Just 4, mchildren = Just 9 }),
         Sue 11 (defRemembered { mvizslas = Just 5, mperfumes = Just 8, mcars = Just 10 }),
         Sue 12 (defRemembered { mchildren = Just 10, mcars = Just 6, mperfumes = Just 5 }),
         Sue 13 (defRemembered { mcats = Just 4, msamoyeds = Just 7, mpomeranians = Just 8 }),
         Sue 14 (defRemembered { mperfumes = Just 6, mgoldfish = Just 10, mchildren = Just 7 }),
         Sue 15 (defRemembered { mperfumes = Just 4, mpomeranians = Just 3, mcars = Just 6 }),
         Sue 16 (defRemembered { mperfumes = Just 7, mcars = Just 9, mpomeranians = Just 6 }),
         Sue 17 (defRemembered { mgoldfish = Just 3, mcars = Just 6, mvizslas = Just 7 }),
         Sue 18 (defRemembered { mperfumes = Just 6, mcars = Just 7, mgoldfish = Just 3 }),
         Sue 19 (defRemembered { mtrees = Just 0, makitas = Just 3, mpomeranians = Just 8 }),
         Sue 20 (defRemembered { mgoldfish = Just 6, mtrees = Just 2, makitas = Just 6 }),
         Sue 21 (defRemembered { mpomeranians = Just 9, makitas = Just 9, msamoyeds = Just 9 }),
         Sue 22 (defRemembered { mvizslas = Just 2, mcars = Just 9, mperfumes = Just 5 }),
         Sue 23 (defRemembered { mgoldfish = Just 10, msamoyeds = Just 8, mchildren = Just 9 }),
         Sue 24 (defRemembered { makitas = Just 4, mgoldfish = Just 1, mvizslas = Just 5 }),
         Sue 25 (defRemembered { mgoldfish = Just 10, mtrees = Just 8, mperfumes = Just 6 }),
         Sue 26 (defRemembered { mvizslas = Just 5, makitas = Just 8, mtrees = Just 1 }),
         Sue 27 (defRemembered { mtrees = Just 3, mcars = Just 6, mperfumes = Just 2 }),
         Sue 28 (defRemembered { mgoldfish = Just 8, mtrees = Just 7, makitas = Just 10 }),
         Sue 29 (defRemembered { mchildren = Just 5, mtrees = Just 1, mgoldfish = Just 10 }),
         Sue 30 (defRemembered { mvizslas = Just 3, mperfumes = Just 8, makitas = Just 3 }),
         Sue 31 (defRemembered { mcars = Just 6, mchildren = Just 10, mperfumes = Just 7 }),
         Sue 32 (defRemembered { mcars = Just 10, mperfumes = Just 3, mgoldfish = Just 10 }),
         Sue 33 (defRemembered { mperfumes = Just 9, mvizslas = Just 3, makitas = Just 4 }),
         Sue 34 (defRemembered { mperfumes = Just 10, mvizslas = Just 7, mchildren = Just 8 }),
         Sue 35 (defRemembered { mcars = Just 5, mperfumes = Just 5, mvizslas = Just 9 }),
         Sue 36 (defRemembered { mtrees = Just 9, mcars = Just 9, makitas = Just 7 }),
         Sue 37 (defRemembered { msamoyeds = Just 9, mperfumes = Just 2, mcars = Just 10 }),
         Sue 38 (defRemembered { makitas = Just 7, mcars = Just 5, mtrees = Just 5 }),
         Sue 39 (defRemembered { mgoldfish = Just 8, mtrees = Just 9, mcars = Just 10 }),
         Sue 40 (defRemembered { mtrees = Just 0, mcats = Just 1, mpomeranians = Just 1 }),
         Sue 41 (defRemembered { mpomeranians = Just 6, mperfumes = Just 9, msamoyeds = Just 1 }),
         Sue 42 (defRemembered { mvizslas = Just 6, makitas = Just 3, mpomeranians = Just 1 }),
         Sue 43 (defRemembered { mvizslas = Just 2, mperfumes = Just 3, mpomeranians = Just 6 }),
         Sue 44 (defRemembered { makitas = Just 5, mpomeranians = Just 0, mvizslas = Just 10 }),
         Sue 45 (defRemembered { mvizslas = Just 4, mgoldfish = Just 1, mcars = Just 5 }),
         Sue 46 (defRemembered { mcars = Just 4, mvizslas = Just 8, mcats = Just 0 }),
         Sue 47 (defRemembered { mcats = Just 5, mchildren = Just 8, mpomeranians = Just 2 }),
         Sue 48 (defRemembered { mvizslas = Just 3, mperfumes = Just 6, mcats = Just 0 }),
         Sue 49 (defRemembered { makitas = Just 7, mperfumes = Just 0, mtrees = Just 7 }),
         Sue 50 (defRemembered { mtrees = Just 4, makitas = Just 10, mvizslas = Just 2 }),
         Sue 51 (defRemembered { mgoldfish = Just 10, mcars = Just 9, mtrees = Just 4 }),
         Sue 52 (defRemembered { mcars = Just 5, mchildren = Just 9, mperfumes = Just 0 }),
         Sue 53 (defRemembered { mvizslas = Just 5, mcars = Just 3, mcats = Just 8 }),
         Sue 54 (defRemembered { mcars = Just 5, makitas = Just 1, mgoldfish = Just 10 }),
         Sue 55 (defRemembered { makitas = Just 10, mvizslas = Just 2, mcars = Just 6 }),
         Sue 56 (defRemembered { mcats = Just 6, mtrees = Just 0, mcars = Just 4 }),
         Sue 57 (defRemembered { mvizslas = Just 1, makitas = Just 1, msamoyeds = Just 7 }),
         Sue 58 (defRemembered { msamoyeds = Just 6, mvizslas = Just 1, makitas = Just 7 }),
         Sue 59 (defRemembered { makitas = Just 9, mcars = Just 8, mvizslas = Just 1 }),
         Sue 60 (defRemembered { mcars = Just 6, mvizslas = Just 7, mgoldfish = Just 0 }),
         Sue 61 (defRemembered { mpomeranians = Just 5, makitas = Just 6, mvizslas = Just 2 }),
         Sue 62 (defRemembered { msamoyeds = Just 2, mcats = Just 8, mgoldfish = Just 7 }),
         Sue 63 (defRemembered { mvizslas = Just 10, mgoldfish = Just 7, msamoyeds = Just 9 }),
         Sue 64 (defRemembered { mperfumes = Just 2, mtrees = Just 1, makitas = Just 6 }),
         Sue 65 (defRemembered { mcars = Just 8, mperfumes = Just 10, mvizslas = Just 9 }),
         Sue 66 (defRemembered { makitas = Just 8, mvizslas = Just 8, mperfumes = Just 8 }),
         Sue 67 (defRemembered { mgoldfish = Just 7, mcars = Just 9, msamoyeds = Just 9 }),
         Sue 68 (defRemembered { mperfumes = Just 2, mchildren = Just 7, makitas = Just 1 }),
         Sue 69 (defRemembered { mperfumes = Just 7, mvizslas = Just 9, makitas = Just 1 }),
         Sue 70 (defRemembered { msamoyeds = Just 3, mvizslas = Just 1, mtrees = Just 1 }),
         Sue 71 (defRemembered { mvizslas = Just 8, mgoldfish = Just 7, mtrees = Just 9 }),
         Sue 72 (defRemembered { mgoldfish = Just 8, mcars = Just 6, mtrees = Just 9 }),
         Sue 73 (defRemembered { mperfumes = Just 5, mcars = Just 10, msamoyeds = Just 7 }),
         Sue 74 (defRemembered { mpomeranians = Just 4, mperfumes = Just 3, mcars = Just 5 }),
         Sue 75 (defRemembered { msamoyeds = Just 1, mperfumes = Just 1, mpomeranians = Just 1 }),
         Sue 76 (defRemembered { mgoldfish = Just 4, mcats = Just 6, makitas = Just 7 }),
         Sue 77 (defRemembered { mperfumes = Just 5, makitas = Just 4, mvizslas = Just 8 }),
         Sue 78 (defRemembered { mperfumes = Just 4, mcats = Just 3, mchildren = Just 4 }),
         Sue 79 (defRemembered { mvizslas = Just 5, mpomeranians = Just 9, msamoyeds = Just 7 }),
         Sue 80 (defRemembered { mcars = Just 3, msamoyeds = Just 5, mpomeranians = Just 7 }),
         Sue 81 (defRemembered { mvizslas = Just 2, msamoyeds = Just 4, mperfumes = Just 2 }),
         Sue 82 (defRemembered { mtrees = Just 1, makitas = Just 10, mvizslas = Just 9 }),
         Sue 83 (defRemembered { mvizslas = Just 0, makitas = Just 2, msamoyeds = Just 5 }),
         Sue 84 (defRemembered { mperfumes = Just 5, mvizslas = Just 7, mchildren = Just 8 }),
         Sue 85 (defRemembered { mcats = Just 3, mchildren = Just 2, mtrees = Just 0 }),
         Sue 86 (defRemembered { mcars = Just 3, mperfumes = Just 2, mgoldfish = Just 2 }),
         Sue 87 (defRemembered { mtrees = Just 1, makitas = Just 7, mvizslas = Just 0 }),
         Sue 88 (defRemembered { mtrees = Just 1, makitas = Just 2, msamoyeds = Just 1 }),
         Sue 89 (defRemembered { mcars = Just 4, mvizslas = Just 8, makitas = Just 1 }),
         Sue 90 (defRemembered { mperfumes = Just 5, mcats = Just 3, mvizslas = Just 0 }),
         Sue 91 (defRemembered { msamoyeds = Just 7, mcats = Just 6, mgoldfish = Just 8 }),
         Sue 92 (defRemembered { msamoyeds = Just 10, mcats = Just 0, mcars = Just 7 }),
         Sue 93 (defRemembered { mcars = Just 6, makitas = Just 7, msamoyeds = Just 2 }),
         Sue 94 (defRemembered { mperfumes = Just 0, mgoldfish = Just 6, mtrees = Just 9 }),
         Sue 95 (defRemembered { mcars = Just 6, mpomeranians = Just 2, msamoyeds = Just 8 }),
         Sue 96 (defRemembered { mcars = Just 2, mtrees = Just 9, msamoyeds = Just 4 }),
         Sue 97 (defRemembered { mgoldfish = Just 5, mtrees = Just 1, mchildren = Just 0 }),
         Sue 98 (defRemembered { makitas = Just 9, mgoldfish = Just 7, mchildren = Just 6 }),
         Sue 99 (defRemembered { mgoldfish = Just 9, makitas = Just 0, mpomeranians = Just 0 }),
         Sue 100 (defRemembered { msamoyeds = Just 6, mchildren = Just 8, mvizslas = Just 5 }),
         Sue 101 (defRemembered { mvizslas = Just 6, mcars = Just 5, mgoldfish = Just 4 }),
         Sue 102 (defRemembered { mvizslas = Just 6, makitas = Just 2, mperfumes = Just 6 }),
         Sue 103 (defRemembered { msamoyeds = Just 3, makitas = Just 7, mchildren = Just 4 }),
         Sue 104 (defRemembered { mcars = Just 3, mperfumes = Just 10, mcats = Just 6 }),
         Sue 105 (defRemembered { mvizslas = Just 9, mpomeranians = Just 0, mcars = Just 1 }),
         Sue 106 (defRemembered { mcats = Just 6, msamoyeds = Just 8, mpomeranians = Just 5 }),
         Sue 107 (defRemembered { mcars = Just 7, mtrees = Just 4, makitas = Just 10 }),
         Sue 108 (defRemembered { mperfumes = Just 3, mvizslas = Just 1, mgoldfish = Just 9 }),
         Sue 109 (defRemembered { mtrees = Just 6, mcars = Just 8, mgoldfish = Just 5 }),
         Sue 110 (defRemembered { mpomeranians = Just 2, mchildren = Just 1, mvizslas = Just 7 }),
         Sue 111 (defRemembered { makitas = Just 0, mvizslas = Just 8, mcars = Just 0 }),
         Sue 112 (defRemembered { mgoldfish = Just 3, mvizslas = Just 6, makitas = Just 2 }),
         Sue 113 (defRemembered { makitas = Just 10, mpomeranians = Just 7, mperfumes = Just 7 }),
         Sue 114 (defRemembered { mcars = Just 10, mcats = Just 2, mvizslas = Just 8 }),
         Sue 115 (defRemembered { makitas = Just 8, mtrees = Just 1, mvizslas = Just 2 }),
         Sue 116 (defRemembered { mvizslas = Just 2, makitas = Just 7, mperfumes = Just 1 }),
         Sue 117 (defRemembered { mgoldfish = Just 0, mvizslas = Just 10, mtrees = Just 9 }),
         Sue 118 (defRemembered { mtrees = Just 3, mcars = Just 0, mgoldfish = Just 0 }),
         Sue 119 (defRemembered { mperfumes = Just 7, mgoldfish = Just 5, mtrees = Just 9 }),
         Sue 120 (defRemembered { mchildren = Just 9, mvizslas = Just 3, mtrees = Just 5 }),
         Sue 121 (defRemembered { mvizslas = Just 1, mgoldfish = Just 7, makitas = Just 10 }),
         Sue 122 (defRemembered { mperfumes = Just 1, mcars = Just 6, mtrees = Just 1 }),
         Sue 123 (defRemembered { makitas = Just 2, mvizslas = Just 0, mgoldfish = Just 7 }),
         Sue 124 (defRemembered { mvizslas = Just 10, mpomeranians = Just 7, makitas = Just 0 }),
         Sue 125 (defRemembered { mperfumes = Just 4, mcats = Just 5, mvizslas = Just 2 }),
         Sue 126 (defRemembered { mcars = Just 6, msamoyeds = Just 8, makitas = Just 3 }),
         Sue 127 (defRemembered { mtrees = Just 9, mgoldfish = Just 7, makitas = Just 9 }),
         Sue 128 (defRemembered { mcars = Just 8, mtrees = Just 0, mperfumes = Just 2 }),
         Sue 129 (defRemembered { mpomeranians = Just 7, mvizslas = Just 2, mperfumes = Just 6 }),
         Sue 130 (defRemembered { mvizslas = Just 9, mpomeranians = Just 3, mtrees = Just 6 }),
         Sue 131 (defRemembered { mvizslas = Just 7, mcars = Just 9, mperfumes = Just 1 }),
         Sue 132 (defRemembered { makitas = Just 2, mpomeranians = Just 9, mvizslas = Just 7 }),
         Sue 133 (defRemembered { mtrees = Just 9, mpomeranians = Just 10, msamoyeds = Just 0 }),
         Sue 134 (defRemembered { mchildren = Just 4, makitas = Just 10, mperfumes = Just 4 }),
         Sue 135 (defRemembered { mvizslas = Just 1, mcats = Just 1, mtrees = Just 8 }),
         Sue 136 (defRemembered { msamoyeds = Just 7, mcars = Just 8, mgoldfish = Just 5 }),
         Sue 137 (defRemembered { mperfumes = Just 0, mchildren = Just 1, mpomeranians = Just 10 }),
         Sue 138 (defRemembered { mvizslas = Just 4, mperfumes = Just 5, mcars = Just 5 }),
         Sue 139 (defRemembered { mtrees = Just 2, mperfumes = Just 8, mgoldfish = Just 0 }),
         Sue 140 (defRemembered { mcars = Just 10, makitas = Just 5, mgoldfish = Just 7 }),
         Sue 141 (defRemembered { mchildren = Just 4, mtrees = Just 3, mgoldfish = Just 8 }),
         Sue 142 (defRemembered { mcars = Just 8, mperfumes = Just 6, mtrees = Just 7 }),
         Sue 143 (defRemembered { makitas = Just 6, mgoldfish = Just 0, mtrees = Just 10 }),
         Sue 144 (defRemembered { makitas = Just 7, mpomeranians = Just 10, mperfumes = Just 10 }),
         Sue 145 (defRemembered { mtrees = Just 10, mvizslas = Just 3, mgoldfish = Just 4 }),
         Sue 146 (defRemembered { msamoyeds = Just 4, makitas = Just 3, mperfumes = Just 6 }),
         Sue 147 (defRemembered { makitas = Just 8, mperfumes = Just 2, mpomeranians = Just 10 }),
         Sue 148 (defRemembered { mcars = Just 2, mperfumes = Just 0, mgoldfish = Just 8 }),
         Sue 149 (defRemembered { mgoldfish = Just 6, makitas = Just 7, mperfumes = Just 6 }),
         Sue 150 (defRemembered { mcars = Just 2, mpomeranians = Just 5, mperfumes = Just 4 }),
         Sue 151 (defRemembered { mgoldfish = Just 1, mcars = Just 5, mtrees = Just 0 }),
         Sue 152 (defRemembered { mpomeranians = Just 4, mcars = Just 7, mchildren = Just 1 }),
         Sue 153 (defRemembered { mgoldfish = Just 8, mcars = Just 1, mchildren = Just 10 }),
         Sue 154 (defRemembered { mcars = Just 6, mperfumes = Just 8, mtrees = Just 1 }),
         Sue 155 (defRemembered { makitas = Just 4, mperfumes = Just 6, mpomeranians = Just 2 }),
         Sue 156 (defRemembered { mpomeranians = Just 5, mcars = Just 4, makitas = Just 1 }),
         Sue 157 (defRemembered { mcats = Just 5, mcars = Just 9, mgoldfish = Just 8 }),
         Sue 158 (defRemembered { mvizslas = Just 5, msamoyeds = Just 1, mchildren = Just 7 }),
         Sue 159 (defRemembered { mvizslas = Just 1, mperfumes = Just 3, makitas = Just 1 }),
         Sue 160 (defRemembered { mgoldfish = Just 10, mpomeranians = Just 9, mperfumes = Just 5 }),
         Sue 161 (defRemembered { msamoyeds = Just 3, mtrees = Just 7, mcars = Just 2 }),
         Sue 162 (defRemembered { mcars = Just 2, mpomeranians = Just 1, mvizslas = Just 6 }),
         Sue 163 (defRemembered { mvizslas = Just 3, mperfumes = Just 5, makitas = Just 6 }),
         Sue 164 (defRemembered { mvizslas = Just 1, mtrees = Just 0, makitas = Just 5 }),
         Sue 165 (defRemembered { mvizslas = Just 5, mcars = Just 6, mpomeranians = Just 8 }),
         Sue 166 (defRemembered { mcars = Just 10, mperfumes = Just 2, mtrees = Just 9 }),
         Sue 167 (defRemembered { mcars = Just 10, mpomeranians = Just 6, mperfumes = Just 4 }),
         Sue 168 (defRemembered { makitas = Just 7, mtrees = Just 10, mgoldfish = Just 7 }),
         Sue 169 (defRemembered { makitas = Just 1, mperfumes = Just 10, mcars = Just 10 }),
         Sue 170 (defRemembered { makitas = Just 5, msamoyeds = Just 8, mvizslas = Just 6 }),
         Sue 171 (defRemembered { mchildren = Just 3, makitas = Just 2, mvizslas = Just 3 }),
         Sue 172 (defRemembered { mgoldfish = Just 5, mvizslas = Just 5, mperfumes = Just 9 }),
         Sue 173 (defRemembered { mperfumes = Just 5, mgoldfish = Just 10, mtrees = Just 5 }),
         Sue 174 (defRemembered { makitas = Just 5, mvizslas = Just 2, mchildren = Just 7 }),
         Sue 175 (defRemembered { mperfumes = Just 5, mcars = Just 7, msamoyeds = Just 2 }),
         Sue 176 (defRemembered { mcars = Just 8, mvizslas = Just 10, makitas = Just 7 }),
         Sue 177 (defRemembered { mperfumes = Just 7, mchildren = Just 8, mgoldfish = Just 7 }),
         Sue 178 (defRemembered { mcars = Just 1, mpomeranians = Just 9, msamoyeds = Just 0 }),
         Sue 179 (defRemembered { mperfumes = Just 6, mcars = Just 2, mtrees = Just 6 }),
         Sue 180 (defRemembered { mtrees = Just 3, mvizslas = Just 7, mchildren = Just 3 }),
         Sue 181 (defRemembered { mvizslas = Just 8, msamoyeds = Just 2, mtrees = Just 9 }),
         Sue 182 (defRemembered { mperfumes = Just 3, mcats = Just 1, mchildren = Just 5 }),
         Sue 183 (defRemembered { makitas = Just 9, mcats = Just 6, mchildren = Just 3 }),
         Sue 184 (defRemembered { mpomeranians = Just 9, mcars = Just 6, mperfumes = Just 8 }),
         Sue 185 (defRemembered { mvizslas = Just 9, mtrees = Just 0, makitas = Just 9 }),
         Sue 186 (defRemembered { mperfumes = Just 6, mcars = Just 5, mgoldfish = Just 5 }),
         Sue 187 (defRemembered { mperfumes = Just 4, mcats = Just 7, mvizslas = Just 2 }),
         Sue 188 (defRemembered { makitas = Just 7, mcars = Just 4, mchildren = Just 10 }),
         Sue 189 (defRemembered { makitas = Just 0, mgoldfish = Just 7, mvizslas = Just 5 }),
         Sue 190 (defRemembered { makitas = Just 5, mcars = Just 5, mcats = Just 6 }),
         Sue 191 (defRemembered { mcars = Just 6, mchildren = Just 0, mperfumes = Just 3 }),
         Sue 192 (defRemembered { mcats = Just 2, mperfumes = Just 10, mgoldfish = Just 7 }),
         Sue 193 (defRemembered { mtrees = Just 1, mperfumes = Just 0, mcars = Just 8 }),
         Sue 194 (defRemembered { mperfumes = Just 9, mchildren = Just 4, mcats = Just 6 }),
         Sue 195 (defRemembered { makitas = Just 7, mtrees = Just 3, mgoldfish = Just 6 }),
         Sue 196 (defRemembered { mgoldfish = Just 8, mcars = Just 8, msamoyeds = Just 0 }),
         Sue 197 (defRemembered { mcats = Just 0, makitas = Just 10, mvizslas = Just 0 }),
         Sue 198 (defRemembered { mgoldfish = Just 1, mperfumes = Just 3, mcars = Just 8 }),
         Sue 199 (defRemembered { makitas = Just 10, mvizslas = Just 5, msamoyeds = Just 6 }),
         Sue 200 (defRemembered { mpomeranians = Just 9, mgoldfish = Just 9, msamoyeds = Just 7 }),
         Sue 201 (defRemembered { msamoyeds = Just 0, mgoldfish = Just 7, makitas = Just 6 }),
         Sue 202 (defRemembered { mvizslas = Just 0, mgoldfish = Just 2, makitas = Just 1 }),
         Sue 203 (defRemembered { mgoldfish = Just 3, mchildren = Just 0, mvizslas = Just 8 }),
         Sue 204 (defRemembered { mcars = Just 8, mtrees = Just 2, mperfumes = Just 2 }),
         Sue 205 (defRemembered { mcars = Just 4, mperfumes = Just 5, mgoldfish = Just 8 }),
         Sue 206 (defRemembered { mvizslas = Just 3, mtrees = Just 2, makitas = Just 1 }),
         Sue 207 (defRemembered { mcars = Just 7, mgoldfish = Just 5, mtrees = Just 1 }),
         Sue 208 (defRemembered { mgoldfish = Just 1, mcars = Just 6, mvizslas = Just 8 }),
         Sue 209 (defRemembered { mcats = Just 4, mtrees = Just 1, mchildren = Just 0 }),
         Sue 210 (defRemembered { mcats = Just 10, mchildren = Just 0, mperfumes = Just 0 }),
         Sue 211 (defRemembered { mcars = Just 4, mpomeranians = Just 7, msamoyeds = Just 5 }),
         Sue 212 (defRemembered { mcars = Just 2, mpomeranians = Just 10, mtrees = Just 1 }),
         Sue 213 (defRemembered { mtrees = Just 10, mcats = Just 5, mcars = Just 10 }),
         Sue 214 (defRemembered { mperfumes = Just 5, mtrees = Just 1, mvizslas = Just 1 }),
         Sue 215 (defRemembered { makitas = Just 10, mvizslas = Just 8, msamoyeds = Just 8 }),
         Sue 216 (defRemembered { mvizslas = Just 2, mcats = Just 5, mpomeranians = Just 3 }),
         Sue 217 (defRemembered { makitas = Just 10, mperfumes = Just 0, mcats = Just 10 }),
         Sue 218 (defRemembered { mtrees = Just 8, mcats = Just 5, mvizslas = Just 2 }),
         Sue 219 (defRemembered { mgoldfish = Just 10, mperfumes = Just 8, mchildren = Just 2 }),
         Sue 220 (defRemembered { msamoyeds = Just 9, mtrees = Just 8, mvizslas = Just 7 }),
         Sue 221 (defRemembered { mchildren = Just 7, mtrees = Just 6, mcars = Just 6 }),
         Sue 222 (defRemembered { mcats = Just 4, makitas = Just 5, mpomeranians = Just 0 }),
         Sue 223 (defRemembered { mtrees = Just 8, mgoldfish = Just 2, mperfumes = Just 8 }),
         Sue 224 (defRemembered { mpomeranians = Just 9, mcars = Just 8, makitas = Just 5 }),
         Sue 225 (defRemembered { makitas = Just 10, mvizslas = Just 0, mtrees = Just 2 }),
         Sue 226 (defRemembered { makitas = Just 8, mcats = Just 6, mcars = Just 7 }),
         Sue 227 (defRemembered { mtrees = Just 1, makitas = Just 3, mgoldfish = Just 4 }),
         Sue 228 (defRemembered { mpomeranians = Just 6, mcats = Just 3, mgoldfish = Just 3 }),
         Sue 229 (defRemembered { mtrees = Just 10, mperfumes = Just 3, mvizslas = Just 7 }),
         Sue 230 (defRemembered { mperfumes = Just 8, mcars = Just 7, makitas = Just 0 }),
         Sue 231 (defRemembered { mperfumes = Just 10, mgoldfish = Just 4, mcars = Just 6 }),
         Sue 232 (defRemembered { mgoldfish = Just 7, mtrees = Just 3, mcats = Just 2 }),
         Sue 233 (defRemembered { mperfumes = Just 6, mtrees = Just 4, makitas = Just 4 }),
         Sue 234 (defRemembered { mgoldfish = Just 9, mcats = Just 4, mcars = Just 7 }),
         Sue 235 (defRemembered { mpomeranians = Just 6, mvizslas = Just 0, makitas = Just 6 }),
         Sue 236 (defRemembered { msamoyeds = Just 5, mcars = Just 5, mchildren = Just 4 }),
         Sue 237 (defRemembered { mvizslas = Just 10, mcars = Just 4, mgoldfish = Just 4 }),
         Sue 238 (defRemembered { mgoldfish = Just 3, msamoyeds = Just 7, makitas = Just 2 }),
         Sue 239 (defRemembered { mcats = Just 8, mchildren = Just 2, mvizslas = Just 7 }),
         Sue 240 (defRemembered { mcars = Just 9, mperfumes = Just 4, mtrees = Just 9 }),
         Sue 241 (defRemembered { mtrees = Just 8, mvizslas = Just 2, mgoldfish = Just 5 }),
         Sue 242 (defRemembered { mcars = Just 6, mtrees = Just 3, mvizslas = Just 3 }),
         Sue 243 (defRemembered { mcats = Just 6, mchildren = Just 7, mcars = Just 4 }),
         Sue 244 (defRemembered { mcats = Just 10, mperfumes = Just 2, mgoldfish = Just 7 }),
         Sue 245 (defRemembered { makitas = Just 8, mcats = Just 10, mperfumes = Just 8 }),
         Sue 246 (defRemembered { mvizslas = Just 8, makitas = Just 5, mperfumes = Just 10 }),
         Sue 247 (defRemembered { mgoldfish = Just 2, mvizslas = Just 5, makitas = Just 7 }),
         Sue 248 (defRemembered { makitas = Just 3, mperfumes = Just 0, mtrees = Just 10 }),
         Sue 249 (defRemembered { mcats = Just 4, mvizslas = Just 5, mpomeranians = Just 6 }),
         Sue 250 (defRemembered { mchildren = Just 3, mvizslas = Just 7, mperfumes = Just 2 }),
         Sue 251 (defRemembered { mcars = Just 0, mpomeranians = Just 10, mperfumes = Just 0 }),
         Sue 252 (defRemembered { makitas = Just 0, mgoldfish = Just 9, mcars = Just 6 }),
         Sue 253 (defRemembered { mperfumes = Just 7, mcars = Just 4, msamoyeds = Just 5 }),
         Sue 254 (defRemembered { makitas = Just 9, mtrees = Just 10, mcars = Just 4 }),
         Sue 255 (defRemembered { msamoyeds = Just 10, mchildren = Just 6, makitas = Just 7 }),
         Sue 256 (defRemembered { mtrees = Just 8, mgoldfish = Just 8, mperfumes = Just 8 }),
         Sue 257 (defRemembered { mgoldfish = Just 3, makitas = Just 2, mperfumes = Just 6 }),
         Sue 258 (defRemembered { mcats = Just 7, mtrees = Just 0, mvizslas = Just 1 }),
         Sue 259 (defRemembered { mperfumes = Just 7, mcars = Just 7, makitas = Just 7 }),
         Sue 260 (defRemembered { mgoldfish = Just 0, mvizslas = Just 0, msamoyeds = Just 2 }),
         Sue 261 (defRemembered { mvizslas = Just 2, mchildren = Just 2, mcats = Just 3 }),
         Sue 262 (defRemembered { mvizslas = Just 2, mpomeranians = Just 9, msamoyeds = Just 3 }),
         Sue 263 (defRemembered { mcats = Just 1, makitas = Just 3, mvizslas = Just 1 }),
         Sue 264 (defRemembered { mpomeranians = Just 10, mtrees = Just 2, mgoldfish = Just 7 }),
         Sue 265 (defRemembered { msamoyeds = Just 5, mtrees = Just 7, mperfumes = Just 4 }),
         Sue 266 (defRemembered { mperfumes = Just 10, mcars = Just 1, mpomeranians = Just 3 }),
         Sue 267 (defRemembered { mtrees = Just 6, mgoldfish = Just 1, mcars = Just 0 }),
         Sue 268 (defRemembered { mcars = Just 6, msamoyeds = Just 4, mpomeranians = Just 5 }),
         Sue 269 (defRemembered { mgoldfish = Just 3, mvizslas = Just 3, makitas = Just 3 }),
         Sue 270 (defRemembered { mchildren = Just 5, mcats = Just 0, mcars = Just 4 }),
         Sue 271 (defRemembered { mgoldfish = Just 3, mperfumes = Just 8, mpomeranians = Just 7 }),
         Sue 272 (defRemembered { msamoyeds = Just 6, mcars = Just 7, mperfumes = Just 10 }),
         Sue 273 (defRemembered { mtrees = Just 4, mcars = Just 2, mvizslas = Just 7 }),
         Sue 274 (defRemembered { msamoyeds = Just 10, mperfumes = Just 9, mgoldfish = Just 6 }),
         Sue 275 (defRemembered { mcars = Just 4, mtrees = Just 2, mperfumes = Just 7 }),
         Sue 276 (defRemembered { makitas = Just 3, mperfumes = Just 9, mcars = Just 9 }),
         Sue 277 (defRemembered { makitas = Just 8, mvizslas = Just 2, mcats = Just 6 }),
         Sue 278 (defRemembered { mtrees = Just 5, mgoldfish = Just 7, makitas = Just 3 }),
         Sue 279 (defRemembered { mperfumes = Just 9, mcars = Just 8, mvizslas = Just 2 }),
         Sue 280 (defRemembered { mtrees = Just 3, mvizslas = Just 0, mchildren = Just 0 }),
         Sue 281 (defRemembered { mcars = Just 7, mtrees = Just 2, mcats = Just 5 }),
         Sue 282 (defRemembered { mvizslas = Just 4, mcars = Just 10, mcats = Just 3 }),
         Sue 283 (defRemembered { makitas = Just 10, mcats = Just 3, msamoyeds = Just 9 }),
         Sue 284 (defRemembered { mtrees = Just 7, mchildren = Just 5, mgoldfish = Just 6 }),
         Sue 285 (defRemembered { mcars = Just 2, mperfumes = Just 5, mcats = Just 7 }),
         Sue 286 (defRemembered { msamoyeds = Just 5, mtrees = Just 10, mgoldfish = Just 6 }),
         Sue 287 (defRemembered { mgoldfish = Just 10, mperfumes = Just 4, mtrees = Just 7 }),
         Sue 288 (defRemembered { mvizslas = Just 9, mtrees = Just 9, mperfumes = Just 0 }),
         Sue 289 (defRemembered { mtrees = Just 4, mgoldfish = Just 9, mvizslas = Just 8 }),
         Sue 290 (defRemembered { mvizslas = Just 3, mcars = Just 3, mtrees = Just 2 }),
         Sue 291 (defRemembered { mgoldfish = Just 2, makitas = Just 2, mtrees = Just 2 }),
         Sue 292 (defRemembered { mchildren = Just 1, mcars = Just 0, mvizslas = Just 5 }),
         Sue 293 (defRemembered { mtrees = Just 5, makitas = Just 4, mgoldfish = Just 6 }),
         Sue 294 (defRemembered { makitas = Just 3, mvizslas = Just 7, mpomeranians = Just 5 }),
         Sue 295 (defRemembered { mgoldfish = Just 10, mvizslas = Just 3, mtrees = Just 1 }),
         Sue 296 (defRemembered { mcars = Just 2, mtrees = Just 1, makitas = Just 0 }),
         Sue 297 (defRemembered { makitas = Just 10, mvizslas = Just 6, msamoyeds = Just 2 }),
         Sue 298 (defRemembered { mchildren = Just 5, mtrees = Just 1, msamoyeds = Just 9 }),
         Sue 299 (defRemembered { mperfumes = Just 9, mtrees = Just 6, mvizslas = Just 1 }),
         Sue 300 (defRemembered { makitas = Just 7, mpomeranians = Just 6, mvizslas = Just 6 }),
         Sue 301 (defRemembered { mcats = Just 7, mchildren = Just 6, mvizslas = Just 7 }),
         Sue 302 (defRemembered { mtrees = Just 2, mvizslas = Just 7, msamoyeds = Just 4 }),
         Sue 303 (defRemembered { mgoldfish = Just 0, msamoyeds = Just 10, mcars = Just 4 }),
         Sue 304 (defRemembered { mpomeranians = Just 9, mchildren = Just 3, mvizslas = Just 5 }),
         Sue 305 (defRemembered { makitas = Just 8, mvizslas = Just 4, mcars = Just 5 }),
         Sue 306 (defRemembered { makitas = Just 0, mperfumes = Just 2, mpomeranians = Just 10 }),
         Sue 307 (defRemembered { makitas = Just 9, mcars = Just 0, mtrees = Just 2 }),
         Sue 308 (defRemembered { mvizslas = Just 10, mgoldfish = Just 8, makitas = Just 6 }),
         Sue 309 (defRemembered { mtrees = Just 0, mcats = Just 6, mperfumes = Just 2 }),
         Sue 310 (defRemembered { mvizslas = Just 10, mcars = Just 1, mtrees = Just 4 }),
         Sue 311 (defRemembered { mgoldfish = Just 8, mperfumes = Just 6, mcats = Just 3 }),
         Sue 312 (defRemembered { mgoldfish = Just 0, mchildren = Just 1, makitas = Just 2 }),
         Sue 313 (defRemembered { mpomeranians = Just 10, mtrees = Just 6, msamoyeds = Just 6 }),
         Sue 314 (defRemembered { mvizslas = Just 5, makitas = Just 4, mpomeranians = Just 2 }),
         Sue 315 (defRemembered { mgoldfish = Just 7, mtrees = Just 0, makitas = Just 5 }),
         Sue 316 (defRemembered { mgoldfish = Just 4, mvizslas = Just 5, mcars = Just 7 }),
         Sue 317 (defRemembered { mperfumes = Just 7, mcats = Just 10, mcars = Just 4 }),
         Sue 318 (defRemembered { msamoyeds = Just 10, mcars = Just 9, mtrees = Just 7 }),
         Sue 319 (defRemembered { mpomeranians = Just 8, mvizslas = Just 6, mcars = Just 3 }),
         Sue 320 (defRemembered { mcars = Just 4, mcats = Just 9, makitas = Just 4 }),
         Sue 321 (defRemembered { mcars = Just 6, mtrees = Just 2, mperfumes = Just 6 }),
         Sue 322 (defRemembered { mgoldfish = Just 1, mcats = Just 2, mperfumes = Just 4 }),
         Sue 323 (defRemembered { makitas = Just 6, mcats = Just 5, mcars = Just 8 }),
         Sue 324 (defRemembered { mcats = Just 4, mvizslas = Just 9, makitas = Just 0 }),
         Sue 325 (defRemembered { mchildren = Just 8, msamoyeds = Just 9, mtrees = Just 4 }),
         Sue 326 (defRemembered { mvizslas = Just 2, msamoyeds = Just 10, mperfumes = Just 7 }),
         Sue 327 (defRemembered { mgoldfish = Just 7, mpomeranians = Just 4, makitas = Just 10 }),
         Sue 328 (defRemembered { mperfumes = Just 8, mcats = Just 4, makitas = Just 10 }),
         Sue 329 (defRemembered { mtrees = Just 0, mcars = Just 9, mgoldfish = Just 3 }),
         Sue 330 (defRemembered { mtrees = Just 5, msamoyeds = Just 7, mperfumes = Just 8 }),
         Sue 331 (defRemembered { mcars = Just 4, mperfumes = Just 2, mgoldfish = Just 0 }),
         Sue 332 (defRemembered { mvizslas = Just 4, mpomeranians = Just 7, makitas = Just 1 }),
         Sue 333 (defRemembered { makitas = Just 4, mgoldfish = Just 3, mperfumes = Just 0 }),
         Sue 334 (defRemembered { msamoyeds = Just 3, makitas = Just 10, mvizslas = Just 0 }),
         Sue 335 (defRemembered { mgoldfish = Just 1, makitas = Just 7, mvizslas = Just 6 }),
         Sue 336 (defRemembered { mperfumes = Just 1, mgoldfish = Just 1, mpomeranians = Just 8 }),
         Sue 337 (defRemembered { mchildren = Just 5, mcars = Just 4, mcats = Just 4 }),
         Sue 338 (defRemembered { mvizslas = Just 5, mcars = Just 10, mcats = Just 3 }),
         Sue 339 (defRemembered { mtrees = Just 2, mgoldfish = Just 3, mcars = Just 1 }),
         Sue 340 (defRemembered { mtrees = Just 10, mgoldfish = Just 6, mperfumes = Just 2 }),
         Sue 341 (defRemembered { makitas = Just 5, mtrees = Just 6, mcats = Just 3 }),
         Sue 342 (defRemembered { mcars = Just 10, mchildren = Just 8, mgoldfish = Just 0 }),
         Sue 343 (defRemembered { mcats = Just 2, makitas = Just 0, mpomeranians = Just 4 }),
         Sue 344 (defRemembered { mperfumes = Just 1, mvizslas = Just 3, mcars = Just 3 }),
         Sue 345 (defRemembered { msamoyeds = Just 8, mcats = Just 5, mperfumes = Just 8 }),
         Sue 346 (defRemembered { mcars = Just 5, makitas = Just 10, mtrees = Just 2 }),
         Sue 347 (defRemembered { mvizslas = Just 9, makitas = Just 9, mcars = Just 3 }),
         Sue 348 (defRemembered { mcars = Just 3, mperfumes = Just 1, mpomeranians = Just 9 }),
         Sue 349 (defRemembered { makitas = Just 1, mcars = Just 4, mperfumes = Just 0 }),
         Sue 350 (defRemembered { mperfumes = Just 8, mvizslas = Just 2, mtrees = Just 6 }),
         Sue 351 (defRemembered { mpomeranians = Just 5, makitas = Just 9, mcats = Just 8 }),
         Sue 352 (defRemembered { mpomeranians = Just 8, mvizslas = Just 3, mgoldfish = Just 10 }),
         Sue 353 (defRemembered { mtrees = Just 2, mpomeranians = Just 0, mgoldfish = Just 6 }),
         Sue 354 (defRemembered { mcats = Just 5, makitas = Just 7, mgoldfish = Just 6 }),
         Sue 355 (defRemembered { mgoldfish = Just 6, mchildren = Just 4, mtrees = Just 10 }),
         Sue 356 (defRemembered { mchildren = Just 1, mtrees = Just 3, makitas = Just 7 }),
         Sue 357 (defRemembered { mtrees = Just 2, msamoyeds = Just 10, mgoldfish = Just 3 }),
         Sue 358 (defRemembered { msamoyeds = Just 10, mcats = Just 0, mgoldfish = Just 0 }),
         Sue 359 (defRemembered { mperfumes = Just 3, mchildren = Just 6, mpomeranians = Just 1 }),
         Sue 360 (defRemembered { mcars = Just 10, mpomeranians = Just 1, msamoyeds = Just 5 }),
         Sue 361 (defRemembered { msamoyeds = Just 9, mpomeranians = Just 7, mperfumes = Just 6 }),
         Sue 362 (defRemembered { mgoldfish = Just 6, mtrees = Just 8, mperfumes = Just 9 }),
         Sue 363 (defRemembered { msamoyeds = Just 10, mpomeranians = Just 9, mchildren = Just 10 }),
         Sue 364 (defRemembered { mperfumes = Just 3, mgoldfish = Just 7, mcars = Just 9 }),
         Sue 365 (defRemembered { mcats = Just 3, mchildren = Just 4, msamoyeds = Just 8 }),
         Sue 366 (defRemembered { mtrees = Just 0, mcars = Just 10, mvizslas = Just 10 }),
         Sue 367 (defRemembered { mpomeranians = Just 10, mchildren = Just 8, mperfumes = Just 2 }),
         Sue 368 (defRemembered { mcars = Just 5, mvizslas = Just 0, msamoyeds = Just 3 }),
         Sue 369 (defRemembered { mtrees = Just 1, mgoldfish = Just 8, mcars = Just 8 }),
         Sue 370 (defRemembered { mvizslas = Just 0, mcars = Just 2, mperfumes = Just 5 }),
         Sue 371 (defRemembered { mtrees = Just 2, mcars = Just 3, mvizslas = Just 8 }),
         Sue 372 (defRemembered { mtrees = Just 10, mchildren = Just 9, mcats = Just 1 }),
         Sue 373 (defRemembered { mpomeranians = Just 3, mperfumes = Just 1, mvizslas = Just 0 }),
         Sue 374 (defRemembered { mvizslas = Just 0, mperfumes = Just 6, mtrees = Just 0 }),
         Sue 375 (defRemembered { mvizslas = Just 7, mpomeranians = Just 1, makitas = Just 10 }),
         Sue 376 (defRemembered { mvizslas = Just 8, mtrees = Just 2, mcars = Just 10 }),
         Sue 377 (defRemembered { mperfumes = Just 9, mcats = Just 5, mgoldfish = Just 5 }),
         Sue 378 (defRemembered { mcats = Just 0, makitas = Just 10, mperfumes = Just 9 }),
         Sue 379 (defRemembered { mcars = Just 4, makitas = Just 1, mtrees = Just 1 }),
         Sue 380 (defRemembered { mcars = Just 4, mperfumes = Just 5, mtrees = Just 3 }),
         Sue 381 (defRemembered { mgoldfish = Just 3, makitas = Just 5, msamoyeds = Just 9 }),
         Sue 382 (defRemembered { mgoldfish = Just 7, mperfumes = Just 5, mtrees = Just 5 }),
         Sue 383 (defRemembered { makitas = Just 4, mcats = Just 6, mcars = Just 8 }),
         Sue 384 (defRemembered { mchildren = Just 6, mgoldfish = Just 10, makitas = Just 7 }),
         Sue 385 (defRemembered { makitas = Just 7, mvizslas = Just 5, mperfumes = Just 10 }),
         Sue 386 (defRemembered { mchildren = Just 7, mvizslas = Just 10, makitas = Just 10 }),
         Sue 387 (defRemembered { mgoldfish = Just 6, makitas = Just 7, mtrees = Just 2 }),
         Sue 388 (defRemembered { mvizslas = Just 6, mtrees = Just 1, makitas = Just 2 }),
         Sue 389 (defRemembered { mcars = Just 5, mvizslas = Just 3, makitas = Just 7 }),
         Sue 390 (defRemembered { mvizslas = Just 4, mcats = Just 8, mperfumes = Just 7 }),
         Sue 391 (defRemembered { makitas = Just 3, mtrees = Just 0, mchildren = Just 2 }),
         Sue 392 (defRemembered { mcats = Just 7, mcars = Just 3, mchildren = Just 9 }),
         Sue 393 (defRemembered { mtrees = Just 10, mvizslas = Just 3, mgoldfish = Just 7 }),
         Sue 394 (defRemembered { mperfumes = Just 0, mgoldfish = Just 7, makitas = Just 4 }),
         Sue 395 (defRemembered { mcats = Just 6, mcars = Just 7, mvizslas = Just 0 }),
         Sue 396 (defRemembered { mvizslas = Just 4, mperfumes = Just 6, mgoldfish = Just 5 }),
         Sue 397 (defRemembered { mpomeranians = Just 8, mtrees = Just 1, makitas = Just 9 }),
         Sue 398 (defRemembered { mgoldfish = Just 7, mpomeranians = Just 6, msamoyeds = Just 9 }),
         Sue 399 (defRemembered { mperfumes = Just 10, mcars = Just 1, mtrees = Just 8 }),
         Sue 400 (defRemembered { mtrees = Just 0, mgoldfish = Just 9, mchildren = Just 6 }),
         Sue 401 (defRemembered { mtrees = Just 1, mcars = Just 6, mpomeranians = Just 8 }),
         Sue 402 (defRemembered { mperfumes = Just 9, mcars = Just 0, mvizslas = Just 10 }),
         Sue 403 (defRemembered { msamoyeds = Just 4, makitas = Just 1, mvizslas = Just 9 }),
         Sue 404 (defRemembered { mperfumes = Just 0, mtrees = Just 2, mcars = Just 4 }),
         Sue 405 (defRemembered { makitas = Just 0, mperfumes = Just 5, msamoyeds = Just 4 }),
         Sue 406 (defRemembered { makitas = Just 8, mvizslas = Just 6, mchildren = Just 2 }),
         Sue 407 (defRemembered { mchildren = Just 1, mtrees = Just 8, mgoldfish = Just 10 }),
         Sue 408 (defRemembered { mpomeranians = Just 4, mtrees = Just 10, mcars = Just 9 }),
         Sue 409 (defRemembered { mperfumes = Just 5, mvizslas = Just 5, makitas = Just 4 }),
         Sue 410 (defRemembered { mtrees = Just 1, makitas = Just 10, mvizslas = Just 6 }),
         Sue 411 (defRemembered { msamoyeds = Just 0, mgoldfish = Just 9, mperfumes = Just 7 }),
         Sue 412 (defRemembered { mgoldfish = Just 7, msamoyeds = Just 10, mtrees = Just 1 }),
         Sue 413 (defRemembered { msamoyeds = Just 0, mpomeranians = Just 10, mvizslas = Just 6 }),
         Sue 414 (defRemembered { mchildren = Just 2, mcars = Just 10, msamoyeds = Just 2 }),
         Sue 415 (defRemembered { mtrees = Just 2, mgoldfish = Just 8, mcars = Just 0 }),
         Sue 416 (defRemembered { msamoyeds = Just 4, mgoldfish = Just 9, mtrees = Just 2 }),
         Sue 417 (defRemembered { mtrees = Just 8, makitas = Just 10, mperfumes = Just 3 }),
         Sue 418 (defRemembered { msamoyeds = Just 9, mgoldfish = Just 2, mcars = Just 1 }),
         Sue 419 (defRemembered { makitas = Just 2, mperfumes = Just 8, mtrees = Just 2 }),
         Sue 420 (defRemembered { mchildren = Just 3, mgoldfish = Just 6, mperfumes = Just 5 }),
         Sue 421 (defRemembered { makitas = Just 8, mperfumes = Just 2, msamoyeds = Just 6 }),
         Sue 422 (defRemembered { mvizslas = Just 10, makitas = Just 4, mpomeranians = Just 3 }),
         Sue 423 (defRemembered { mcats = Just 8, mperfumes = Just 3, mtrees = Just 4 }),
         Sue 424 (defRemembered { mcars = Just 2, mchildren = Just 4, mpomeranians = Just 8 }),
         Sue 425 (defRemembered { mpomeranians = Just 4, msamoyeds = Just 2, mgoldfish = Just 4 }),
         Sue 426 (defRemembered { mperfumes = Just 6, mcars = Just 4, mgoldfish = Just 4 }),
         Sue 427 (defRemembered { makitas = Just 0, mgoldfish = Just 7, mperfumes = Just 5 }),
         Sue 428 (defRemembered { mperfumes = Just 4, mcars = Just 3, makitas = Just 5 }),
         Sue 429 (defRemembered { mtrees = Just 0, mvizslas = Just 0, mgoldfish = Just 1 }),
         Sue 430 (defRemembered { mperfumes = Just 4, mvizslas = Just 2, mcars = Just 7 }),
         Sue 431 (defRemembered { mgoldfish = Just 7, mpomeranians = Just 8, mtrees = Just 0 }),
         Sue 432 (defRemembered { mgoldfish = Just 7, mchildren = Just 9, mtrees = Just 3 }),
         Sue 433 (defRemembered { makitas = Just 1, mvizslas = Just 10, mtrees = Just 2 }),
         Sue 434 (defRemembered { mperfumes = Just 2, mcars = Just 4, mgoldfish = Just 10 }),
         Sue 435 (defRemembered { mpomeranians = Just 6, mvizslas = Just 9, mtrees = Just 1 }),
         Sue 436 (defRemembered { mcars = Just 9, mtrees = Just 0, mgoldfish = Just 0 }),
         Sue 437 (defRemembered { mtrees = Just 1, mgoldfish = Just 1, mvizslas = Just 8 }),
         Sue 438 (defRemembered { mgoldfish = Just 7, msamoyeds = Just 8, mchildren = Just 2 }),
         Sue 439 (defRemembered { mchildren = Just 1, mcats = Just 7, mvizslas = Just 8 }),
         Sue 440 (defRemembered { mcats = Just 2, mpomeranians = Just 6, mgoldfish = Just 4 }),
         Sue 441 (defRemembered { mperfumes = Just 7, mcats = Just 3, mvizslas = Just 6 }),
         Sue 442 (defRemembered { makitas = Just 4, msamoyeds = Just 5, mcars = Just 2 }),
         Sue 443 (defRemembered { makitas = Just 3, mperfumes = Just 3, mcats = Just 9 }),
         Sue 444 (defRemembered { mperfumes = Just 10, makitas = Just 6, mtrees = Just 0 }),
         Sue 445 (defRemembered { mcars = Just 5, mchildren = Just 9, mperfumes = Just 8 }),
         Sue 446 (defRemembered { mvizslas = Just 10, mcars = Just 3, mperfumes = Just 5 }),
         Sue 447 (defRemembered { mchildren = Just 9, mperfumes = Just 1, mcars = Just 10 }),
         Sue 448 (defRemembered { makitas = Just 0, mgoldfish = Just 8, mtrees = Just 3 }),
         Sue 449 (defRemembered { mcars = Just 7, makitas = Just 8, mchildren = Just 3 }),
         Sue 450 (defRemembered { mcars = Just 4, makitas = Just 9, mcats = Just 0 }),
         Sue 451 (defRemembered { mperfumes = Just 4, msamoyeds = Just 5, mgoldfish = Just 6 }),
         Sue 452 (defRemembered { mperfumes = Just 10, makitas = Just 1, mcars = Just 7 }),
         Sue 453 (defRemembered { mtrees = Just 1, mgoldfish = Just 3, mvizslas = Just 6 }),
         Sue 454 (defRemembered { mgoldfish = Just 8, mpomeranians = Just 6, mtrees = Just 10 }),
         Sue 455 (defRemembered { makitas = Just 5, mvizslas = Just 8, mgoldfish = Just 10 }),
         Sue 456 (defRemembered { mcats = Just 5, mtrees = Just 4, msamoyeds = Just 0 }),
         Sue 457 (defRemembered { mperfumes = Just 8, mcars = Just 0, mcats = Just 3 }),
         Sue 458 (defRemembered { makitas = Just 1, mtrees = Just 10, mvizslas = Just 2 }),
         Sue 459 (defRemembered { mvizslas = Just 6, makitas = Just 3, mchildren = Just 10 }),
         Sue 460 (defRemembered { mperfumes = Just 7, mtrees = Just 9, mgoldfish = Just 8 }),
         Sue 461 (defRemembered { mchildren = Just 6, mvizslas = Just 4, mperfumes = Just 5 }),
         Sue 462 (defRemembered { mvizslas = Just 6, makitas = Just 8, mperfumes = Just 9 }),
         Sue 463 (defRemembered { mgoldfish = Just 8, mcars = Just 4, mtrees = Just 10 }),
         Sue 464 (defRemembered { mpomeranians = Just 8, mcars = Just 5, mvizslas = Just 0 }),
         Sue 465 (defRemembered { mcats = Just 10, mgoldfish = Just 7, makitas = Just 1 }),
         Sue 466 (defRemembered { mcats = Just 2, mchildren = Just 1, mcars = Just 6 }),
         Sue 467 (defRemembered { mperfumes = Just 3, msamoyeds = Just 6, mcars = Just 0 }),
         Sue 468 (defRemembered { msamoyeds = Just 10, mpomeranians = Just 6, mtrees = Just 2 }),
         Sue 469 (defRemembered { mchildren = Just 2, mperfumes = Just 2, mpomeranians = Just 4 }),
         Sue 470 (defRemembered { mcats = Just 1, mperfumes = Just 5, mvizslas = Just 9 }),
         Sue 471 (defRemembered { mvizslas = Just 5, mperfumes = Just 2, makitas = Just 7 }),
         Sue 472 (defRemembered { msamoyeds = Just 8, mgoldfish = Just 6, mcats = Just 1 }),
         Sue 473 (defRemembered { mgoldfish = Just 10, mperfumes = Just 9, mcars = Just 4 }),
         Sue 474 (defRemembered { msamoyeds = Just 0, mcars = Just 4, mvizslas = Just 4 }),
         Sue 475 (defRemembered { mtrees = Just 2, mcars = Just 7, makitas = Just 8 }),
         Sue 476 (defRemembered { mvizslas = Just 3, mperfumes = Just 5, mgoldfish = Just 1 }),
         Sue 477 (defRemembered { mcats = Just 7, mcars = Just 4, mtrees = Just 1 }),
         Sue 478 (defRemembered { mvizslas = Just 8, makitas = Just 3, mgoldfish = Just 0 }),
         Sue 479 (defRemembered { mcars = Just 6, mcats = Just 3, mperfumes = Just 2 }),
         Sue 480 (defRemembered { mgoldfish = Just 1, mchildren = Just 9, mvizslas = Just 3 }),
         Sue 481 (defRemembered { mpomeranians = Just 5, mvizslas = Just 1, mcars = Just 10 }),
         Sue 482 (defRemembered { mchildren = Just 5, mperfumes = Just 5, mcats = Just 1 }),
         Sue 483 (defRemembered { mperfumes = Just 2, mgoldfish = Just 7, mtrees = Just 6 }),
         Sue 484 (defRemembered { makitas = Just 2, mgoldfish = Just 4, mperfumes = Just 10 }),
         Sue 485 (defRemembered { msamoyeds = Just 3, mgoldfish = Just 0, makitas = Just 1 }),
         Sue 486 (defRemembered { mtrees = Just 8, mvizslas = Just 9, mgoldfish = Just 0 }),
         Sue 487 (defRemembered { mgoldfish = Just 8, msamoyeds = Just 0, mtrees = Just 0 }),
         Sue 488 (defRemembered { mperfumes = Just 7, mcars = Just 5, mtrees = Just 0 }),
         Sue 489 (defRemembered { mvizslas = Just 3, mpomeranians = Just 2, mperfumes = Just 5 }),
         Sue 490 (defRemembered { mcars = Just 5, mperfumes = Just 5, makitas = Just 5 }),
         Sue 491 (defRemembered { mchildren = Just 8, mtrees = Just 1, mpomeranians = Just 4 }),
         Sue 492 (defRemembered { mpomeranians = Just 0, makitas = Just 1, mvizslas = Just 8 }),
         Sue 493 (defRemembered { makitas = Just 10, mperfumes = Just 10, msamoyeds = Just 8 }),
         Sue 494 (defRemembered { mperfumes = Just 6, mvizslas = Just 4, mcats = Just 6 }),
         Sue 495 (defRemembered { mchildren = Just 6, mpomeranians = Just 5, msamoyeds = Just 4 }),
         Sue 496 (defRemembered { mvizslas = Just 1, mtrees = Just 5, makitas = Just 1 }),
         Sue 497 (defRemembered { mvizslas = Just 10, mperfumes = Just 10, mpomeranians = Just 3 }),
         Sue 498 (defRemembered { msamoyeds = Just 3, mtrees = Just 2, mcars = Just 5 }),
         Sue 499 (defRemembered { mcats = Just 6, mchildren = Just 3, mperfumes = Just 0 }),
         Sue 500 (defRemembered { mpomeranians = Just 10, mcats = Just 3, mvizslas = Just 5 })]

target :: Known        
target = Known {
           children = 3,
           cats = 7,
           samoyeds = 2,
           pomeranians = 3,
           akitas = 0,
           vizslas = 0,
           goldfish = 5,
           trees = 3,
           cars = 2,
           perfumes = 1
         }
        
isPossibleMatch :: Bool -> Known -> Remembered -> Bool
isPossibleMatch advanced known remembered =
    match1 children mchildren &&
    match2 cats mcats &&
    match1 samoyeds msamoyeds &&
    match3 pomeranians mpomeranians &&
    match1 akitas makitas &&
    match1 vizslas mvizslas &&
    match3 goldfish mgoldfish &&
    match2 trees mtrees &&
    match1 cars mcars &&
    match1 perfumes mperfumes
    where
      matcher2' = if advanced then matcher2 else matcher1
      matcher3' = if advanced then matcher3 else matcher1
      match1 k r = matcher1 (k known) (r remembered)
      match2 k r = matcher2' (k known) (r remembered)
      match3 k r = matcher3' (k known) (r remembered)

matcher1 :: Int -> Maybe Int -> Bool
matcher1 k Nothing = True
matcher1 k (Just r) = k == r

matcher2 :: Int -> Maybe Int -> Bool
matcher2 k Nothing = True
matcher2 k (Just r) = k < r

matcher3 :: Int -> Maybe Int -> Bool
matcher3 k Nothing = True
matcher3 k (Just r) = k > r
                  
reconcile :: Bool -> [Sue] -> Known -> Maybe Sue
reconcile advanced sues known =
    listToMaybe (filter (\(Sue _ r) -> isPossibleMatch advanced known r) sues)

findSue :: Bool -> [Sue] -> Known -> Int
findSue advanced sues known = case reconcile advanced sues known of
                                Nothing -> error "No possible Sue found"
                                Just (Sue n _) -> n
           
main :: IO ()
main = do
  print (findSue False input target)
  print (findSue True input target)
